syntax = "Lua54"
column_width = 80
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"
space_after_function_names = "Never"

[sort_requires]
enabled = false
